default_stages: [ "pre-commit", "commit-msg", "pre-push" ]
default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: requirements-txt-fixer

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --ignore-init-module-imports

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3
        args:
            - --line-length=100

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args:
        - --profile=black

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
        args: ["--manifest-path", "from_variants/Cargo.toml", "--"]
    -   id: cargo-check
        args: ["--manifest-path", "from_variants/Cargo.toml"]
    -   id: fmt
        args: ["--manifest-path", "type-checker/Cargo.toml", "--"]
    -   id: cargo-check
        args: ["--manifest-path", "type-checker/Cargo.toml"]
    -   id: fmt
        args: ["--manifest-path", "lowering/Cargo.toml", "--"]
    -   id: cargo-check
        args: ["--manifest-path", "lowering/Cargo.toml"]
    -   id: fmt
        args: ["--manifest-path", "optimization/Cargo.toml", "--"]
    -   id: cargo-check
        args: ["--manifest-path", "optimization/Cargo.toml"]
    -   id: fmt
        args: ["--manifest-path", "translation/Cargo.toml", "--"]
    -   id: cargo-check
        args: ["--manifest-path", "translation/Cargo.toml"]
    -   id: fmt
        args: ["--manifest-path", "emission/Cargo.toml", "--"]
    -   id: cargo-check
        args: ["--manifest-path", "emission/Cargo.toml"]
    -   id: fmt
        args: ["--manifest-path", "pipeline/Cargo.toml", "--"]
    -   id: cargo-check
        args: ["--manifest-path", "pipeline/Cargo.toml"]

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args:
          - -i
          - "--style={BasedOnStyle: llvm, IndentWidth: 4}"
      - id: cppcheck
        args:
          - --language=c++
          - --suppress=unusedFunction
          - --suppress=missingIncludeSystem
          - --suppress=unmatchedSuppression
          - --suppress=unusedStructMember
          - --suppress=unusedVariable
          - --suppress=useStlAlgorithm
          - --suppress=memleak
          - --suppress=uninitvar
          - --suppress=constVariable
          - --suppress=unassignedVariable
          - --suppress=nullPointerRedundantCheck
          - --inline-suppr
