[package]
name = "optimization"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.31"
translation = { version = "0.1.0", path = "../translation" }
itertools = "0.14.0"
lowering = { version = "0.1.0", path = "../lowering" }
test-case = "3.3.1"
