[package]
name = "compilation"
version = "0.1.0"
edition = "2021"

[dependencies]
from_variants = { version = "0.1.0", path = "../from_variants" }
itertools = "0.14.0"
lowering = { version = "0.1.0", path = "../lowering" }
once_cell = "1.20.2"
test-case = "3.3.1"
