name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Python dependencies
      run: |
        pip install -r requirements-dev.txt

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        rustflags: " "
        toolchain: nightly

    - name: Install C++ dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgtest-dev librange-v3-dev

    - name: Temporary Script
      run: |
        echo '#include "main/include.hpp"' > backend/include/main/main.hpp
        echo 'struct Main : TypedClosureI<Empty, Int> { using TypedClosureI<Empty, Int>::TypedClosureI; LazyT<Int> body() override { return make_lazy<Int>(0); } static std::unique_ptr<TypedFnI<Int>> init(const ArgsT &args, std::shared_ptr<void>) { return std::make_unique<Main>(args);}};' >> backend/include/main/main.hpp

    - name: Build
      run: |
        make

    - name: Run Tests
      run: |
        make test
