name: Lint

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        rustflags: " "

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cppcheck clang-format-14

    - name: Install pre-commit
      run: |
        pip install pre-commit
        pre-commit install

    - name: Lint Files
      run: |
        pre-commit run --all-files
